### ISSUE TITLE
Navbar user dropdown is hidden by other components

### ISSUE THREAD

**Issue by danuja01** [danuja01/AF_PROJECT_G34#9]
user dropdown in the navbar is getting hidden by other components on the page. This seems to be because the z-index of the navbar is lower than that of the other components. As a result, the user dropdown is not visible when it is clicked.

### Steps to reproduce:

1. Go to any page on the website.
2. Click on the user dropdown in the navbar.
3. Notice that the dropdown is hidden behind other components on the page.

### Expected behavior:

- The user dropdown should be visible and on top of all other components on the page when it is clicked.

### Proposed solution:

Increase the z-index of the navbar so that it is higher than that of other components on the page. This should ensure that the user dropdown is visible when it is clicked.

**Comment by ashish-khankari** [comment]
Could You assign me this task, I would love to contribute

**Comment by danuja01** [comment]
> Could You assign me this task, I would love to contribute

Hi Ashish,
Sorry the issue is already fixed but if u want i can assign you to a another issue,  When navigating through the navigation bar on the website, the appropriate navigation link does not get highlighted. would you like to contribute?
